int baseCSSSize = 1145;
String baseCSS(
  "body,header,nav{display:grid;}"
  "header,footer,#menuButton{background-color:#303050;}"
  "header,footer,.menuButton,.name,.mail{color:#fff;}"
  "body{user-select:none;margin:0;padding:0;height:100vh;grid-template-rows:auto 1fr auto;grid-template-areas:\"header\"\"main\"\"footer\";}"
  "header{grid-area:header;align-self:flex-start;height:55px;column-gap:10px;}"
  "nav{grid-template-columns:repeat(3,120px);margin-top:32px;margin-left:auto;margin-right:auto;text-align:center;padding:0;}"
  ".menuButton{margin:0;padding-left:5px;padding-right:5px;text-decoration:none;font-size:20px;border-color:white;border-width:2px;border-style:solid;border-top:none;}"
  ".menuButton:hover{box-shadow:inset 0 0 7px #fff;border-width:3px;}"
  "main{grid-area:main;grid-gap:10px;padding:20px;text-align:center;box-shadow:inset 0 0 2px #303050,inset 0 0 5px #303050,inset 0 0 10px #303050;order:4;display:flex;flex-direction:column;}"
  "footer{grid-area:footer;align-self:flex-end;text-align:right;padding:5px;}"
  ".name{position:absolute;top:5px;left:10px;font-size:23px;}"
  ".mail{text-decoration:none;font-size:15px;margin-right:5px;}"
  ".mail:hover{text-shadow:0 0 10px #fff;}"
  ".content{width:auto;}"
);

int homeCSSSize = 1004;
String homeCSS(" main {"
" flex-direction: row;"
" flex-wrap: wrap;"
" justify-content: center;"
" align-items: stretch;"
" font-size: 20px;"
" }"
""
" .bodyPart,"
" .line,"
" .item {"
" border-radius: 5px;"
" padding: 10px;"
" }"
""
" .bodyPart,"
" .item {"
" text-align: left;"
" border: 2px;"
" border-style: solid;"
" box-shadow: 0 0 10px #303050;"
" display: flex;"
" align-items: flex-start;"
" flex: 1;"
" flex-wrap: wrap;"
" align-items: stretch;"
" }"
""
" .bodyPart {"
" flex-direction: column;"
" }"
""
" .item {"
" flex-direction: row;"
" margin: 5px;"
" grid-gap: 10px;"
" }"
""
" .line {"
" background-color: #303050;"
" color: white;"
" display: flex;"
" grid-gap: 10px;"
" margin: 5px;"
" width: calc(100% - 30px);"
" }"
""
" input {"
" font-size: 18px;"
" }"
""
" a.button {"
" align-content: center;"
" padding: 1px 6px;"
" width: 200px;"
" height: 200px;"
" border-radius: 20px;"
" background-color: #303050;"
" color: white;"
" text-decoration: none;"
" text-align: center;"
" font-family: sans-serif;"
" font-weight: bold;"
" font-size: 60px;"
" }"
""
" a.button:hover {"
" background-color: #3c3c62;"
" }"
""
" a.button:active"
" {"
" width: 160px;"
" height: 160px;"
" background-color: #303050;"
" border: 20px solid #3c3c62;"
" }"
""
);

int settinsCSSSize = 1032;
String settingsCSS(
  " main {"
" flex-direction: row;"
" flex-wrap: wrap;"
" justify-content: center;"
" align-items: stretch;"
" font-size: 20px;"
" }"
""
" .contentForm {"
" width: 100%;"
" }"
""
" .bodyPart,"
" .wifi,"
" .item,"
" .modLabel,"
" .config {"
" border-radius: 5px;"
" padding: 10px;"
" }"
""
" .bodyPart,"
" .wifi,"
" .item {"
" text-align: left;"
" border: 2px;"
" border-style: solid;"
" box-shadow: 0 0 10px #303050;"
" display: flex;"
" align-items: flex-start;"
" flex: 1;"
" }"
""
" .bodyPart {"
" flex-direction: column;"
" flex-wrap: wrap;"
" align-items: stretch;"
" }"
""
" .wifi,"
" .item {"
" flex-direction: column;"
" margin: 5px;"
" }"
""
" #ap {"
" max-height: 115px;"
" }"
""
" #inForm {"
" display: flex;"
" flex-direction: row;"
" grid-gap: 10px;"
" }"
""
" .ip {"
" width: 30px;"
" appearance: none;"
" text-align: center;"
" }"
""
" input[type=number]::-webkit-outer-spin-button,"
" input[type=number]::-webkit-inner-spin-button {"
" -webkit-appearance: none;"
" margin: 0;"
" }"
""
" input[type=number] {"
" -moz-appearance: textfield;"
" }"
""
" .wifi {"
" max-height: calc(100vh - 500px);"
" min-height: 100px;"
" overflow-x: hidden;"
" overflow-y: auto;"
" flex-grow: 1;"
" }"
""
" .modLabel,"
" .config {"
" background-color: #303050;"
" color: white;"
" display: flex;"
" grid-gap: 10px;"
" margin: 5px;"
" width: calc(100% - 30px);"
" }"
""
" .config {"
" /* flex-direction: column;*/"
" flex-wrap: wrap;"
" width: 100% - 20px;"
" }"
""
" .ssid {"
" display: inline-block;"
" width: 100%;"
" padding: 5px;"
" }"
""
" .ssid input[type=radio] {"
" display: none;"
" }"
""
" .ssid label {"
" display: inline-block;"
" cursor: pointer;"
" user-select: none;"
" width: calc(100% - 25px);"
" }"
""
" .ssid input[type=radio]:checked+label {"
" background-color: #303050;"
" color: #fff;"
" box-shadow: inset 0 0 3px #fff;"
" border-radius: 5px;"
" padding: 5px;"
" padding-left: 10px;"
" }"
""
" input {"
" font-size: 18px;"
" }"
);
